version: "3.9"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      # MYSQL_ROOT_PASSWORD : root
      MYSQL_USER : root
      MYSQL_PASSWORD: diahaufa123
      MYSQL_DATABASE: belee_test

    adminer:
      image: adminer
      restart: always
      ports:
        - 9191:8080

    app:
      container_name: api_belee
      build: .
      restart: always
      ports:
        - 8080:8080
      volumes:
        - .:/usr/src/app
