# contoh github workflow untuk github actions (CI)


name : unit test golang
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'

jobs:
  # namanya terserah
  # job 1 : unit test
  unit-test:
    name: "do unit test to project go"
    # kalo bisa alpine, alpine aja
    runs-on: ubuntu-latest
    steps:
    - name: setup github action (CI)
      uses: actions/checkout@v2
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: running unit test
      # test menggunakan go test -cover
      run: go test ./... -cover
  
  build-push-docker:
    name: "build image and push to registry"
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - uses: actions/checkout@v2
    - name: build docker
      run: docker build -t 2010010700/belee:1.0.0 .
    - name: login registry docker hub
      





